In [1]:
import numpy as np

In [3]:
array=np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array[0:5]

array([0, 1, 2, 3, 4])

In [7]:
array[0:5]=10
array

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

Copying array

In [12]:
array_copy=array.copy()
array_copy

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [14]:
array_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
array_2d[0]

array([ 5, 10, 15])

In [16]:
array_2d[1][2]

30

In [21]:
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [24]:
arr=np.zeros([10,10])
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
length=arr.shape[0]

In [31]:
for i in range(length):
    arr[i]=i

In [32]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [33]:
arr[[1,2,3]]#fancy indexing

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])