In [3]:
import numpy as np
from __future__ import division

In [4]:
5/2

2.5

In [7]:
arr1=np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [8]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [9]:
arr1+arr1

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [10]:
5/arr1

array([[5.        , 2.5       , 1.66666667, 1.25      ],
       [0.625     , 0.55555556, 0.5       , 0.45454545]])

In [11]:
5*arr1

array([[ 5, 10, 15, 20],
       [40, 45, 50, 55]])

In [12]:
5**arr1

array([[       5,       25,      125,      625],
       [  390625,  1953125,  9765625, 48828125]], dtype=int32)