In [1]:
import numpy as np

In [2]:
arr=np.arange(11)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
A=np.random.randn(10)#random normal distri

In [6]:
B=np.random.randn(10)#random normal distri

binary functions

In [9]:
np.add(A,B)

array([ 1.34852881, -1.36765567, -0.24072987,  0.38048151, -1.11766992,
        0.44130291,  0.42676962,  1.19074385,  0.51800141,  1.24132673])

In [10]:
np.maximum(A,B)

array([ 1.96721466, -0.65133222,  0.41259912,  0.8919239 , -0.52395998,
        0.35745044,  0.99305715,  1.43395559,  2.37742006,  1.25314169])

In [13]:
website="https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html"
import webbrowser
webbrowser.open(website)

True