In [1]:
import numpy as np

In [4]:
my_list=[1,2,3,4]
my_array=np.array([1,2,3,4])

In [5]:
my_list

[1, 2, 3, 4]

In [6]:
my_array

array([1, 2, 3, 4])

In [7]:
my_array.shape

(4,)

In [8]:
my_array.dtype

dtype('int32')

In [9]:
my_array.size

4

In [13]:
my_array2=np.array([my_list,my_list])
my_array2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
zeros2=np.zeros([5,5])
zeros2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros2.dtype

dtype('float64')

In [20]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])