In [1]:
import numpy as np

In [3]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('mynp',arr)#save as file

In [14]:
np.savetxt('mynp.txt',arr,delimiter=",")#save as file

In [17]:
arr=np.loadtxt('mynp.txt',delimiter=",")
arr

array([0., 1., 2., 3., 4.])

In [6]:
arr1=np.load('mynp.npy')

In [7]:
np.savez('ziparray.npz',x=arr,y=arr1)

In [11]:
achieve_array=np.load('ziparray.npz')
achieve_array['x']
achieve_array['y']

array([0, 1, 2, 3, 4])